# Project information
site_name: LeetCodeAlchemy
site_url: https://github.com/diptu/LeetCodeAlchemy
site_author: Nazmul Alam
site_description: >-
  My digital laboratory for mastering algorithms and data structures through LeetCode.

# Repository
repo_name: diptu/LeetCodeAlchemy
repo_url: https://github.com/diptu/LeetCodeAlchemy

# Copyright
copyright: Copyright &copy; 2025 - 2025 Nazmul Alam

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - user guide: getting-started.md
    - License: LICENSE.md
  - Tutorials:
      - Topics : tutorials/index.md
      - Hash Table: tutorials/hashtable/index.md
